management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always

server:
  port: 8080

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  data.redis.database: 0
  data.redis.host: localhost
  data.redis.password:
  data.redis.port: 6379
  threads:
    virtual:
      enabled: true