management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    database: 0
    host: localhost
    port: 6379
    password: